In [ ]:
import numpy as np

In [2]:
np.arange(0,6,1)

array([0, 1, 2, 3, 4, 5])

In [3]:
np.ones(4)

array([1., 1., 1., 1.])

In [4]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#make array in numpy
list=[1,3,4,5]

In [6]:
array=np.array(list)
array

array([1, 3, 4, 5])

In [7]:
#cast matrix into array
matrix=[[1,3,6],[6,8,7]]

In [8]:
np.array(matrix)

array([[1, 3, 6],
       [6, 8, 7]])

In [9]:
np.linspace(0,5,56)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        , 1.09090909, 1.18181818, 1.27272727,
       1.36363636, 1.45454545, 1.54545455, 1.63636364, 1.72727273,
       1.81818182, 1.90909091, 2.        , 2.09090909, 2.18181818,
       2.27272727, 2.36363636, 2.45454545, 2.54545455, 2.63636364,
       2.72727273, 2.81818182, 2.90909091, 3.        , 3.09090909,
       3.18181818, 3.27272727, 3.36363636, 3.45454545, 3.54545455,
       3.63636364, 3.72727273, 3.81818182, 3.90909091, 4.        ,
       4.09090909, 4.18181818, 4.27272727, 4.36363636, 4.45454545,
       4.54545455, 4.63636364, 4.72727273, 4.81818182, 4.90909091,
       5.        ])

In [11]:
#numpy operation
arr=np.arange(0,35)

In [12]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68])

In [13]:
arr*arr

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156])

In [14]:
arr/arr

C:\Program Files\anaconda2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68])

In [17]:
arr**2

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156], dtype=int32)

In [18]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189])

#numpy slicing

In [20]:
a=np.arange(0,8)

In [22]:
a[7]

7

In [24]:
a[1:5]

array([1, 2, 3, 4])

In [25]:
a[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [27]:
slice=a[0:6]
slice

array([0, 1, 2, 3, 4, 5])

In [28]:
#array in matrix
b=np.array([[1,3,6],[5,7,4],[2,3,2]])

In [29]:
b

array([[1, 3, 6],
       [5, 7, 4],
       [2, 3, 2]])

In [33]:
b[2]

array([2, 3, 2])

In [34]:
b[1][1]

7

In [37]:
b[:2,1:]

array([[3, 6],
       [7, 4]])

In [38]:
b[:2]

array([[1, 3, 6],
       [5, 7, 4]])