In [ ]:
#seven different ways we can genrate array of data

In [2]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [4]:
z=np.zeros(10)#10 times zero print
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
z=np.zeros((10,10))#10 by 10 matrix
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
a=np.ones((10,10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
r=np.random.random((10,10))
r# random number gives between 0 to 1

array([[0.6372011 , 0.28442193, 0.25404311, 0.95363002, 0.40878053,
        0.25077469, 0.99392384, 0.37900117, 0.82207779, 0.03343988],
       [0.09549215, 0.75388868, 0.76519974, 0.2098452 , 0.95199894,
        0.38034192, 0.11918173, 0.31845043, 0.8684855 , 0.58864344],
       [0.07633437, 0.4215036 , 0.69699122, 0.02476106, 0.26405355,
        0.32608809, 0.55356598, 0.67521521, 0.30032007, 0.58214803],
       [0.53869314, 0.83872143, 0.96656068, 0.93013765, 0.30386396,
        0.57459135, 0.74512395, 0.11211765, 0.95085404, 0.24397116],
       [0.86160091, 0.56273025, 0.58023977, 0.95904527, 0.60268881,
        0.73838041, 0.64764609, 0.27514895, 0.3584238 , 0.39207168],
       [0.65673188, 0.63420874, 0.70350018, 0.42106309, 0.92407657,
        0.77974331, 0.78296814, 0.55928618, 0.23937982, 0.60756843],
       [0.63157959, 0.73612153, 0.89765415, 0.95941714, 0.14466706,
        0.2914401 , 0.61463318, 0.29450214, 0.04658163, 0.25107769],
       [0.27792018, 0.51583697, 0.1085913

In [9]:
g=np.random.randn(10,10)
g

array([[ 1.26101146,  0.69624089,  0.13204988,  0.14509942, -0.86397749,
        -0.11922863, -0.4906869 ,  1.00875752,  1.24923629,  0.78740653],
       [-0.39182035,  0.46358654, -0.6505845 , -0.35328008, -0.4746343 ,
        -0.26851022, -0.8796923 , -0.9183424 ,  1.34577423, -1.06054403],
       [-0.37877484, -0.74800721, -0.76349035, -0.74487694, -0.32114205,
         0.83342063,  0.73238775,  1.88398742, -0.59507081,  1.19755186],
       [-0.20745869, -0.1167775 , -0.38325588,  0.70649074, -0.07479641,
        -0.87895476, -0.77673346,  0.85555328,  0.74111791,  1.84733131],
       [-1.21462639,  0.25256257, -0.1412428 , -0.9605608 ,  1.30170087,
         0.49805628, -1.44739413, -0.06718802,  0.37586739, -0.72073352],
       [ 1.1355889 ,  0.68104819,  0.43707656, -0.78098616,  1.07265662,
        -0.43544499, -1.76959891,  0.89233049, -0.17386156, -0.66377662],
       [ 2.23563033, -1.23773873, -0.89271073,  0.82132989, -0.78837743,
        -0.36509843,  0.69401617,  1.40183444

In [10]:
g.mean()

0.042612031275216455

In [11]:
g.var()

0.8806179162630561