In [1]:
import numpy as np
a=np.array([[3,2],[1,4]])
a

array([[3, 2],
       [1, 4]])

In [2]:
ainv=np.linalg.inv(a)
ainv#inverse matrix

array([[ 0.4, -0.2],
       [-0.1,  0.3]])

In [3]:
a.dot(ainv)

array([[1., 0.],
       [0., 1.]])

In [4]:
#matrix determinante
np.linalg.det(a)

10.000000000000002

In [5]:
np.diag(a)#diagonal matrix

array([3, 4])

In [6]:
np.diag([3,2])

array([[3, 0],
       [0, 2]])

In [7]:
b=np.array([3,2])
b

array([3, 2])

In [8]:
d=np.array([1,4])
d

array([1, 4])

In [9]:
np.outer(b,d)

array([[ 3, 12],
       [ 2,  8]])

In [10]:
np.inner(b,d)

11

In [11]:
b.dot(d)

11

In [12]:
np.diag(a).sum()

7

In [20]:
np.trace(a)

7

In [22]:
x=np.random.randn(100,3)
x

array([[-1.79009532e+00,  2.69845403e-01,  2.08630021e+00],
       [ 2.48437881e-01, -7.93695205e-01,  1.44546112e+00],
       [ 7.66121225e-01, -1.79911308e-01,  3.54265962e-01],
       [-3.20670888e-01,  3.90585535e-01,  1.65469334e+00],
       [-5.55333901e-01,  1.41925363e+00, -4.89222825e-02],
       [ 5.59544057e-01, -8.23976739e-01,  7.86246343e-01],
       [-7.69262635e-01, -1.06411308e+00, -1.77245300e+00],
       [ 4.42392025e-01, -1.81271532e-01, -1.66924099e+00],
       [-3.26013585e-01, -9.66727457e-01, -9.99835966e-01],
       [ 8.50191888e-01, -7.32011948e-01,  5.82222579e-01],
       [-8.25293822e-01, -1.38904401e+00,  6.98899725e-01],
       [ 1.78553771e+00,  7.31298388e-01,  1.66387762e+00],
       [-1.71325947e-01, -8.50901035e-01, -1.20474647e+00],
       [ 8.99415934e-01,  1.48456779e-01,  1.23181005e-01],
       [-7.52865738e-01, -1.09080939e+00, -6.53876860e-01],
       [-1.15169396e-01, -3.86455548e-01,  1.63745552e+00],
       [-9.54630528e-01, -8.18708160e-01

In [15]:
cov=np.cov(x)
cov

array([[ 0.32144878, -0.55446694, -0.12855833, ...,  0.0342295 ,
        -0.06139707,  0.1638101 ],
       [-0.55446694,  0.95640067,  0.22296603, ..., -0.05947065,
         0.10640157, -0.28316516],
       [-0.12855833,  0.22296603,  2.01913933, ..., -0.70670045,
         0.83018099, -1.05140278],
       ...,
       [ 0.0342295 , -0.05947065, -0.70670045, ...,  0.24771575,
        -0.29027056,  0.36466278],
       [-0.06139707,  0.10640157,  0.83018099, ..., -0.29027056,
         0.34156658, -0.43493103],
       [ 0.1638101 , -0.28316516, -1.05140278, ...,  0.36466278,
        -0.43493103,  0.57743803]])

In [17]:
cov.shape

(100, 100)

In [24]:
cov=np.cov(x.T)
cov

array([[ 1.12741746,  0.05014805, -0.05989502],
       [ 0.05014805,  0.99518771,  0.04989619],
       [-0.05989502,  0.04989619,  1.10989197]])

In [25]:
np.linalg.eigh(cov)

(array([0.94932585, 1.10378688, 1.1793844 ]),
 array([[-0.37036026,  0.51960556, -0.76996321],
        [ 0.83890231,  0.54301833, -0.03706767],
        [-0.39884356,  0.6596523 ,  0.63701071]]))

In [26]:
a

array([[3, 2],
       [1, 4]])

In [27]:
b

array([3, 2])

In [29]:
b=np.array([3,2])
b

array([3, 2])

In [31]:
v=np.linalg.inv(a).dot(b)
v

array([0.8, 0.3])

In [32]:
c=np.linalg.solve(a,b)
c

array([0.8, 0.3])