In [3]:
import pandas as pd
import numpy as np
a=np.array([[1,6,5],[8,6,5],[8,5,9]])
a

array([[1, 6, 5],
       [8, 6, 5],
       [8, 5, 9]])

In [5]:
from sklearn.preprocessing import MinMaxScaler

In [7]:
ma=MinMaxScaler([0,8])

In [10]:
ma.fit_transform(a)

C:\Program Files\anaconda2\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0., 8., 0.],
       [8., 8., 0.],
       [8., 0., 8.]])

In [12]:
b=np.array([[1,2],[7,8]])
b

array([[1, 2],
       [7, 8]])

In [14]:
from sklearn.preprocessing import StandardScaler

In [17]:
s=StandardScaler()

In [19]:
s.fit_transform(a)

C:\Program Files\anaconda2\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Program Files\anaconda2\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-1.41421356,  0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678, -0.70710678],
       [ 0.70710678, -1.41421356,  1.41421356]])

In [21]:
from sklearn.preprocessing import Normalizer

In [23]:
n=Normalizer()

In [24]:
n.fit_transform(a)

array([[0.12700013, 0.76200076, 0.63500064],
       [0.71554175, 0.53665631, 0.4472136 ],
       [0.61357199, 0.38348249, 0.69026849]])