In [2]:
import numpy as np 
a = np.array([1,2,3]) 
print(a)

[1 2 3]


In [4]:
import numpy as numpy

a=numpy.array([1,2,3])
print(a)


[1 2 3]


In [7]:

print("\n2-D Array")
b=np.array([[1,5],[2,3]])
print(b)


2-D Array
[[1 5]
 [2 3]]


In [10]:
print("\n3-D ARRAY")
c=np.array([[[1,2,3],[2,3,4],[3,4,5]]])
print(c)


3-D ARRAY
[[[1 2 3]
  [2 3 4]
  [3 4 5]]]


In [26]:
print('\n\n')
a = np.array([1, 3], dtype = complex) 
print(a)





[1.+0.j 3.+0.j]


In [30]:
print('\n\n')
a = np.arange(9).reshape(3,3)
print(a)




[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [33]:
print('First array:') 
print(a) 
print('\n')  

print('second array')
b=np.array([5,5,5])
print(b)

print('add')
c=np.add(a,b)
print(c)

First array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


second array
[5 5 5]
add
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
