In [3]:
import numpy as np
m=np.array([[1,2],[3,4]])#list of list to instalizing matrix.1index is row,2nd is clm

In [4]:
l=[[1,2],[3,4]]

In [5]:
l[0]

[1, 2]

In [6]:
l[0][0]

1

In [7]:
m[0][0]

1

In [9]:
m[0,0]

1

In [10]:
m2=np.matrix([[1,2],[3,4]])
m2

matrix([[1, 2],
        [3, 4]])

In [12]:
a=np.array(m2)
a

array([[1, 2],
       [3, 4]])

In [14]:
a.T//transose matrix

array([[1, 3],
       [2, 4]])