In [1]:
##libraries  used tensorflow>2.0 and keras

In [2]:
from keras.preprocessing.text import one_hot

Using TensorFlow backend.


In [3]:
#tensorflow>2.0
from tensorflow.keras.preprocessing.text import one_hot#use for converting sentence into one hot encoder

In [4]:
##sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'i am a good developer',
     'your video are good',
     'understand the meaning of words',
     'i am good girl']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good developer',
 'your video are good',
 'understand the meaning of words',
 'i am good girl']

In [6]:

voc_size=10000#define dictonary size,this is vocabulary size

In [8]:
#one hot  representation
onehot_rep=[one_hot(words,voc_size)for words in sent]#i pass sentence which are presented word and to pass the one_hot function 
print(onehot_rep)#convert each sentence into index. see 1st and 2nd sentence are similar but some word are different and this index size also change and which word are same having this word index size also same
#only last index of 1st two sentence are changed.

[[1440, 4334, 8976, 3181], [1440, 4334, 8976, 2654], [1440, 7060, 8976, 9795], [42, 5120, 3924, 5997, 8718], [376, 4362, 1923, 5997], [9318, 1440, 3021, 8976, 2802], [42, 5120, 5997, 6609]]


In [9]:
#word embedding representation for creating embedding matrix
#feature representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences#use for size of sentence
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8#length of sentence size are fixed
embedded_docs=pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)#padding as a pre means add 0 in the front /starting point .if padding as a post then zeros add ending
print(embedded_docs)#try to compelte 8 word sentence sent_length is 8.

[[   0    0    0    0 1440 4334 8976 3181]
 [   0    0    0    0 1440 4334 8976 2654]
 [   0    0    0    0 1440 7060 8976 9795]
 [   0    0    0   42 5120 3924 5997 8718]
 [   0    0    0    0  376 4362 1923 5997]
 [   0    0    0 9318 1440 3021 8976 2802]
 [   0    0    0    0   42 5120 5997 6609]]


In [12]:
dim=15#dimension intialized means features

In [15]:
model=Sequential()#intialized sequential layer
model.add(Embedding(voc_size,10,input_length=sent_length))#addd embedding layer best on demsion featurized representation
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [20]:
embedded_docs[0]#this is 1st sentence

array([   0,    0,    0,    0, 1440, 4334, 8976, 3181])

In [22]:
print(model.predict(embedded_docs)[0])#1 st sentence all word are convert into dimension of 10 vectors.1st 'o' are convert into dimension of 10 vector
#1st 4 word line are same bcoz 1st 4 word are zero

[[ 0.00370898  0.01676655 -0.01289026  0.03681915  0.02653073  0.04935506
  -0.00273293 -0.00405405  0.02758516  0.04574449]
 [ 0.00370898  0.01676655 -0.01289026  0.03681915  0.02653073  0.04935506
  -0.00273293 -0.00405405  0.02758516  0.04574449]
 [ 0.00370898  0.01676655 -0.01289026  0.03681915  0.02653073  0.04935506
  -0.00273293 -0.00405405  0.02758516  0.04574449]
 [ 0.00370898  0.01676655 -0.01289026  0.03681915  0.02653073  0.04935506
  -0.00273293 -0.00405405  0.02758516  0.04574449]
 [-0.0069731   0.0224548  -0.03895143  0.01867492 -0.03186945 -0.0143011
   0.00912946  0.01309497  0.01685265 -0.00072289]
 [ 0.01739627  0.00900223 -0.02226016  0.02398494 -0.03836275 -0.01490932
  -0.0450284   0.0344685  -0.03914039 -0.03638558]
 [-0.0230641  -0.00778332 -0.02250675 -0.04506993  0.04058187  0.04651413
  -0.01896671 -0.00291974  0.03860868 -0.04116359]
 [-0.03747736  0.04178396  0.0436015   0.01159384  0.04342283 -0.01662376
   0.04474813 -0.00437521 -0.04856141  0.03068861]]


In [23]:
print(model.predict(embedded_docs))

[[[ 0.00370898  0.01676655 -0.01289026  0.03681915  0.02653073
    0.04935506 -0.00273293 -0.00405405  0.02758516  0.04574449]
  [ 0.00370898  0.01676655 -0.01289026  0.03681915  0.02653073
    0.04935506 -0.00273293 -0.00405405  0.02758516  0.04574449]
  [ 0.00370898  0.01676655 -0.01289026  0.03681915  0.02653073
    0.04935506 -0.00273293 -0.00405405  0.02758516  0.04574449]
  [ 0.00370898  0.01676655 -0.01289026  0.03681915  0.02653073
    0.04935506 -0.00273293 -0.00405405  0.02758516  0.04574449]
  [-0.0069731   0.0224548  -0.03895143  0.01867492 -0.03186945
   -0.0143011   0.00912946  0.01309497  0.01685265 -0.00072289]
  [ 0.01739627  0.00900223 -0.02226016  0.02398494 -0.03836275
   -0.01490932 -0.0450284   0.0344685  -0.03914039 -0.03638558]
  [-0.0230641  -0.00778332 -0.02250675 -0.04506993  0.04058187
    0.04651413 -0.01896671 -0.00291974  0.03860868 -0.04116359]
  [-0.03747736  0.04178396  0.0436015   0.01159384  0.04342283
   -0.01662376  0.04474813 -0.00437521 -0.048561